### ISSUE TITLE
Personalized application in job board

### ISSUE THREAD

**Issue by fontvu** [troppdus/MyWorstJobApp#1]
Hello,

I came across the readme file and noticed there is a thing called "personalized application". What does that mean? Especially in the case of job board, what is the difference between applying with a standard profile and personalized application?

**Comment by RaniaOj** [comment]
Hii, 
it´s about the search. There will be 3 options to find a specific job:
- use the search bar and type for exemple "IT-support" 
- use some kind of filter where you can specify the Job field, the city and job type, here  in our exemple job field "IT" , city "Berlin", job type: "full-time"
- or use both of them for a better search result

**Comment by fontvu** [comment]
Then the job board is basically a search function where you can search with keyword and filter, isn't it?

**Comment by RaniaOj** [comment]
right you can see all job offers but also search for a specific job with the entered keywords or with the given filter inputs, 
I forgot to notice that in the filter we need one other attirubute: type for specify if it is a full-time or part-time job

**Comment by fontvu** [comment]
Thanks for your clarification, I guess the search page would look similar to [Xing search page](https://www.xing.com/jobs/search). I will close the issue for now but it could be opened the future when we implement the website.
