### ISSUE TITLE
Missing job attributes in the job board

### ISSUE THREAD

**Issue by fontvu** [troppdus/MyWorstJobApp#2]
Hello,

I can see that the applicants and companies' attributes are described in the document such as ID, name, address. However, there is no description for the job itself. I wonder what are they?

I have a few suggestions:
- job name
- company id (employer)
- company name
- location
- job description

**Comment by fontvu** [comment]
I just created a sketch domain model for your reference. The class *application* is also added.

**Comment by troppdus** [comment]
Good morning.

Thank you for pointing out. Yes, we missed that. 
It should also have a jobId, as you have written in the reference. The company name is important too, but I don't think the companyId is needed. Another essential thing is the salary (should be optinal and a range) and a property type of employment.
-> {Full-Time, Part-Time}
And a job field after that you can filter. For example IT, Business economics, Mechanical Engineering, ...

**Comment by fontvu** [comment]
I reckon the job field can be described as category. The *job* class then should have the following attributes
- job name
- company
- location
- salary
- type of employment
- job field (category)

**Comment by troppdus** [comment]
That's looks good.
