### ISSUE TITLE
Domain model confirmation

### ISSUE THREAD

**Issue by ilia-karasev** [troppdus/MyWorstJobApp#4]
The domain model was updated according to the discussion. Please confirm the updated model.

**Comment by troppdus** [comment]
I have to add two things. First, it is required for this assignment to have it as a PNG. Second, I guess it would be better if you had a superclass "User" and two child classes "Applicant" and "Company".

**Comment by RaniaOj** [comment]
right! it may be also then easier for you

**Comment by fontvu** [comment]
> I have to add two things. First, it is required for this assignment to have it as a PNG. Second, I guess it would be better if you had a superclass "User" and two child classes "Applicant" and "Company".

I think the superclass *User* won't work with *Company* class but for now I will just put it together. This is subjected to change later when we actually implement it.

**Comment by troppdus** [comment]
Oh no, there was a misunderstanding. A company is a normal user, exactly like an applicant. They need some basic stuff too. They need to log in too. For this a company requires an userId, a password, and an email. But don't add these properties to the company. Add them to the superclass "User". 
You need to add the new class "Applicant" which extends from User and has most of the properties of the current User class.

By the way, I think owendDocument should be qualification.

**Comment by troppdus** [comment]
Application has nothing to do with the superclass User.

**Comment by fontvu** [comment]
> Oh no, there was a misunderstanding. A company is a normal user, exactly like an applicant. They need some basic stuff too. They need to log in too. For this a company requires an userId, a password, and an email. But don't add these properties to the company. Add them to the superclass "User".  You need to add the new class "Applicant" which extends from User and has most of the properties of the current User class.
> 
> By the way, I think owendDocument should be qualification.

No problem, I have added *Applicant* class. Qualification and CV could be both documents, that why I have these 2 separated.

**Comment by RaniaOj** [comment]
I would just notice that appliedJob can be one or more!
After this little change you can consider this comment as confirmation for the information domain model.

**Comment by troppdus** [comment]
I agree

**Comment by fontvu** [comment]
Thanks @RaniaOj and @troppdus for your input and confirmation. @ishanism and @ilia-karasev please update your UML class accordingly.
