### ISSUE TITLE
Requirements update

### ISSUE THREAD

**Issue by ilia-karasev** [troppdus/MyWorstJobApp#5]
Hi, I have posted the updated requirements as a table below the images in readme.
We thought that IDs for applicants and companies should be generated automatically.
Also, we renamed the concept of "custom applications" to "filters".
Is there anything else that is missing in the table?

**Comment by troppdus** [comment]
Looks good from my side. Maybe @RaniaOj finds something?

**Comment by RaniaOj** [comment]
I confirm too!
